---
title: "Week5Lab"
author: "Group 13 |	Adjusted net national income (constant 2015 US$)"
format: html
editor: visual
---

```{r}
#! include: false
install.packages("gt")
```

```{r}
library(tidyverse)
library(dplyr)
library(conflicted)
library(gt)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::lag)

```

```{r}
readr::read_csv("country_codes.csv")

# Adjusted Net National Income
readr::read_csv("AdjustedNetNationalIncome/API_NY.ADJ.NNTY.KD_DS2_en_csv_v2_3377.csv")
readr::read_csv("AdjustedNetNationalIncome/Metadata_Country_API_NY.ADJ.NNTY.KD_DS2_en_csv_v2_3377.csv")
readr::read_csv("AdjustedNetNationalIncome/Metadata_Indicator_API_NY.ADJ.NNTY.KD_DS2_en_csv_v2_3377.csv")

# World Bank total population
readr::read_csv("world_bank_total_population/Metadata_Indicator_API_SP.POP.TOTL_DS2_en_csv_v2_267553.csv")
readr::read_csv("world_bank_total_population/API_SP.POP.TOTL_DS2_en_csv_v2_267553.csv")
readr::read_csv("world_bank_total_population/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_267553.csv")

```

```{r}
# Task 1.1: Cleaning the Data
clean_up_wb_csv <- function(
    in_file_name,
    out_file_name) {
  
  # Read the CSV starting from row 5.
  wb_data <- read.csv(
    in_file_name,
    skip = 4,
    header = TRUE,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  # Remove completely empty columns
  wb_data <- wb_data[, colSums(!is.na(wb_data) & wb_data != "") > 0]
  
  # Remove completely empty rows
  wb_data <- wb_data[rowSums(!is.na(wb_data) & wb_data != "") > 0, ]
  
  # Clean column names by removing extra spaces
  names(wb_data) <- trimws(names(wb_data))
  
  # Remove rows where Country Name is missing
  if ("Country Name" %in% names(wb_data)) {
    wb_data <- wb_data[wb_data$`Country Name` != "" & !is.na(wb_data$`Country Name`), ]
  }
  
  # Save the cleaned CSV
  write.csv(
    wb_data,
    out_file_name,
    row.names = FALSE
  )
}
```

```{r}
# Task 1.2: Importing the Data as Data Frame
indicator <- clean_up_wb_csv("AdjustedNetNationalIncome/API_NY.ADJ.NNTY.KD_DS2_en_csv_v2_3377.csv", "indicator.csv")

population <- clean_up_wb_csv("world_bank_total_population/API_SP.POP.TOTL_DS2_en_csv_v2_267553.csv", "population.csv")
```


```{R}
country_codes <- read.csv("country_codes.csv")
nrow(indicator)
nrow(population)

reducing_function <- function(
    old_table, new_table, country_codes) {
  new_table <- old_table |>
  semi_join(country_codes, by = c("Country Code" = "country_code"))
}

population_reduced <- reducing_function(population, population_reduced, country_codes)
indicator_reduced <- reducing_function(indicator, indicator_reduced, country_codes)

population_reduced
indicator_reduced
```


```{r}
df_subset <- inner_join(indicator, population, by = "Country Name") |> select("Country Name", "Country Code", "")
df_subset
```

```{r}

```

